### ISSUE TITLE
"Join as a Developer" podria llevar a signup si no estás logueado

### ISSUE THREAD

**Issue by groundhogs** [jenaro94/non-profit-devs#10]
Como developer, esperaba inmediatamente ver con quien podría colaborar. Como mi información mínima es necesaria para hacerlo, esperaba me fuera requerida más o menos inmediatamente antes de loguearme.

**Comment by jenaro94** [comment]
Decis que en vez de redirigir a `/profile` redirija a `/projects`?

**Comment by jenaro94** [comment]
PR submitted, join us should redirect to `/signup`
