### ISSUE TITLE
Add internationalization

### ISSUE THREAD

**Issue by jenaro94** [jenaro94/non-profit-devs#23]
We need to start translating all of the texts, for now, to spanish

**Comment by joelalejandro** [comment]
Happy to help with this!

**Comment by jenaro94** [comment]
Hey! That's awesome, I already pushed a branch called feat/23 where the basic setup is done with react-i18next

**Comment by jenaro94** [comment]
Hey @joelalejandro I assumed you might want to use it, but be my guest, if you want to try with another library it's up for discussion, if you want to create a different approach, that's fine too 👍

**Comment by joelalejandro** [comment]
@jenaro94 `react-i18n` looks perfect! I'm just gonna build on top of that :)
