### ISSUE TITLE
Responsive issue, horizontal scroll using MBP13

### ISSUE THREAD

**Issue by tretapey** [jenaro94/non-profit-devs#8]
When I open the site in firefox in a MBP13 I see a small horizontal scroll. Check screenshot.
<img width="404" alt="Screen Shot 2020-06-25 at 15 30 18" src="https://user-images.githubusercontent.com/5502418/85778460-f7936c80-b6f8-11ea-9481-24f09e28a793.png">

**Comment by jenaro94** [comment]
Fixed :)
